const fs=require('fs'),vm=require('vm'),path=require('path');global.window=global;global.localStorage={getItem:()=>null,setItem:()=>{},removeItem:()=>{}};const root=__dirname;vm.runInThisContext(fs.readFileSync(path.join(root,'5goddesses-datenbank.js'),'utf8'));vm.runInThisContext(fs.readFileSync(path.join(root,'game-engine.js'),'utf8'));const E=global.G5Engine,DB=global.GODDESSES_DB.karten,card=n=>DB.find(c=>c.name===n);let pass=0,fail=0;const ok=(x,m)=>{if(!x)throw Error(m||'assert')};const t=(n,f)=>{try{f();console.log('PASS',n);pass++}catch(e){console.error('FAIL',n,'-',e.message);fail++}};
function rt(n,o=0,fd=false){const c=card(n);if(!c)throw Error('card missing '+n);return {bild:c.bild,owner:o,stufe:c.stufe||1,hearts:c.herzen??0,physicalShield:c.physischer_schild??0,astralShield:c.astraler_schild??0,physical:c.physische_staerke??0,astral:c.astrale_staerke??0,honor:c.ehre??0,ready:true,enteredTurn:0,attackedTurn:null,developedTurn:null,wonderTurn:null,wonderCostCurrent:0,effectState:{},faceDown:fd,developmentStack:[c.bild]}}
function P(i){return {index:i,name:i?'Psilo Cybe':'Brombeerbart',turnCount:3,hand:[],bezSlots:[null,null],equipment:[{weapon:null,shield:null,armor:null,helmet:null},{weapon:null,shield:null,armor:null,helmet:null}],azr:[null,null,null],primary:null,refuge:null,discard:[],stacks:{bezwingerinnen:[],astral:[],ruestkammer:[]},development:[]}}
function S(){return {players:[P(0),P(1)],activePlayer:1,phaseIndex:5,roundSerial:9,sharedSecondary:null,azrLocks:[],log:[],pendingBezEffect:null,pendingDamage:null,attack:null,winner:null}}
function setup(){const s=S();s.players[1].bezSlots[0]=rt('Die brillante Magistratin Strikelyn',1);s.players[0].bezSlots[0]=rt('Die glorreiche Eroberin Martha Kaizer',0);s.players[0].equipment[0].armor=rt('Ubusa Brustpanzer',0);s.players[0].azr[0]=rt('Aufopferung der S.H.I.E.L.D.',0,true);let r=E.prepareAttack(s,0,{type:'bez',slot:0},'physical');ok(r.ok,'prepare attack');return s}
t('Strikelyn attack exposes face-down Aufopferung before combat',()=>{const s=setup();const xs=E.defenderFaceDownSlots(s);ok(xs.includes(0),'Aufopferung not offered')});
t('Attack cannot bypass an unhandled Instinkt reaction',()=>{const s=setup();const r=E.confirmAttack(s);ok(!r.ok&&r.needsReaction,'confirmAttack bypassed reaction');ok(s.phaseIndex===5,'phase advanced too early')});
t('Aufopferung can be revealed and targeted before shield choice',()=>{const s=setup();let r=E.revealDefenderCard(s,0);ok(r.ok,'reveal failed');ok(s.pendingBezEffect?.type==='aufopferung_shield_target','target pending missing');r=E.resolveNewAstralSpellTarget(s,'0');ok(r.ok,'target resolve failed');ok(s.players[0].bezSlots[0].effectState.aufopferungPhysicalShield===1,'physical temp shield missing');ok(!s.pendingDamage,'damage started before combat')});
t('After Aufopferung, physical damage offers temporary shield plus Ubusa/base sources',()=>{const s=setup();E.revealDefenderCard(s,0);E.resolveNewAstralSpellTarget(s,'0');let r=E.confirmAttack(s);ok(r.ok,'confirm after reaction');r=E.resolveCombat(s);ok(r.ok&&r.needsShieldChoice,'shield choice missing');const q=E.currentShieldChoice(s);const labels=q.sources.map(x=>x.label).join('|');ok(labels.includes('Aufopferung der S.H.I.E.L.D.'),'temp shield source missing');ok(labels.includes('Ubusa Brustpanzer'),'Ubusa source missing')});
t('Choosing Aufopferung shield absorbs Strikelyn physical hit before Ubusa',()=>{const s=setup();E.revealDefenderCard(s,0);E.resolveNewAstralSpellTarget(s,'0');E.confirmAttack(s);E.resolveCombat(s);const beforeArmor=s.players[0].equipment[0].armor.physicalShield;const r=E.chooseShieldSource(s,'aufopferung','aufopferungPhysicalShield');ok(r.ok,'temp shield choice failed');ok(s.players[0].equipment[0].armor.physicalShield===beforeArmor,'Ubusa was consumed unexpectedly');ok(Number(s.players[0].bezSlots[0].effectState.aufopferungPhysicalShield||0)===0,'temp shield not consumed')});
t('Defender may explicitly pass Instinkt and then choose Ubusa/base shield normally',()=>{const s=setup();let r=E.passAttackReaction(s);ok(r.ok,'pass failed');r=E.confirmAttack(s);ok(r.ok,'confirm after pass failed');r=E.resolveCombat(s);ok(r.needsShieldChoice,'shield choice missing');const q=E.currentShieldChoice(s);ok(!q.sources.some(x=>x.source==='aufopferung'),'unplayed temp shield appeared');ok(q.sources.some(x=>x.label.includes('Ubusa')),'Ubusa missing')});
t('ASTRAL attack also allows Aufopferung before damage and exposes its ASTRAL shield',()=>{const s=setup();s.attack=null;s.players[1].bezSlots[0].astral=1;let r=E.prepareAttack(s,0,{type:'bez',slot:0},'astral');ok(r.ok);r=E.revealDefenderCard(s,0);ok(r.ok);E.resolveNewAstralSpellTarget(s,'0');E.confirmAttack(s);r=E.resolveCombat(s);ok(r.needsShieldChoice);const q=E.currentShieldChoice(s);ok(q.sources.some(x=>x.source==='aufopferung'),'ASTRAL temp shield missing')});
t('Multiple Instinkt cards keep reaction window open until played or explicitly passed',()=>{const s=setup();s.players[0].azr[1]=rt('Siegel der Kampfschwäche',0,true);E.revealDefenderCard(s,0);E.resolveNewAstralSpellTarget(s,'0');ok(E.defenderFaceDownSlots(s).includes(1),'second instinct not still offered');const r=E.confirmAttack(s);ok(!r.ok&&r.needsReaction,'second reaction was bypassed')});
console.log(`RESULT ${pass} PASS / ${fail} FAIL`);if(fail)process.exit(1);
