const fs=require('fs'),vm=require('vm'),path=require('path'),assert=require('assert/strict');
global.window=global;
global.localStorage={getItem:()=>null,setItem(){},removeItem(){}};
for(const f of ['5goddesses-datenbank.js','game-engine.js','ai-player.js'])vm.runInThisContext(fs.readFileSync(path.join(__dirname,f),'utf8'),{filename:f});
const E=G5Engine,card=n=>GODDESSES_DB.karten.find(c=>c.name===n),spell='Sofortige Zerstörung',staff='Instabiler Stab';
let pass=0,fail=0;
function t(n,f){try{f();console.log('PASS',n);pass++;}catch(e){console.error('FAIL',n,e.message);fail++;}}
function rt(n,owner=0,faceDown=false){const c=card(n);assert(c,n);return {bild:c.bild,owner,faceDown,stufe:c.stufe||1,hearts:c.herzen??0,physical:c.physische_staerke??0,astral:c.astrale_staerke??0,physicalShield:c.physischer_schild??0,astralShield:c.astraler_schild??0,honor:0,ready:true,enteredTurn:0,effectState:{},developmentStack:[c.bild]};}
function P(i){return {index:i,name:'Spieler '+i,turnCount:3,hand:[],bezSlots:[rt('Die glorreiche Eroberin Martha Kaizer',i),null],equipment:[{weapon:null,shield:null,armor:null,helmet:null},{weapon:null,shield:null,armor:null,helmet:null}],azr:[null,null,null],primary:null,refuge:null,discard:[],stacks:{bezwingerinnen:[],astral:[],ruestkammer:[]},development:[]};}
function S(){const s={players:[P(0),P(1)],activePlayer:0,phaseIndex:4,roundSerial:7,log:[],sharedSecondary:null,azrLocks:[],pendingBezEffect:null,pendingDamage:null,attack:null,winner:null};s.players[0].hand=[card(spell).bild];s.players[1].equipment[0].weapon=rt(staff,1);return s;}
function open(s){const r=E.playOpenAzr(s,0,0);assert(r.ok,r.msg);return E.newAstralSpellTargets(s);}
function hit(s,name=staff){const target=E.newAstralSpellTargets(s).find(x=>x.name.includes(name));assert(target,'Ziel fehlt: '+name);const r=E.resolveNewAstralSpellTarget(s,target.id);assert(r.ok,r.msg);}
function discarded(p,n){return p.discard.filter(x=>(typeof x==='string'?x:x.bild)===card(n).bild).length;}
t('Offen aus der Hand: gegnerischen Stab zerstören und beide Karten ablegen',()=>{const s=S();open(s);hit(s);assert.equal(s.players[1].equipment[0].weapon,null);assert.equal(discarded(s.players[1],staff),1);assert.equal(discarded(s.players[0],spell),1);assert.equal(s.pendingBezEffect,null);assert.equal(s.players[0].azr[0],null);});
t('Offenes Ausspielen auch in der Nachschubphase',()=>{const s=S();s.phaseIndex=7;open(s);hit(s);});
t('Stabbonus endet sofort mit der Zerstörung',()=>{const s=S();const before=E.combatStrength(s,1,0,'astral').total;open(s);hit(s);assert.equal(E.combatStrength(s,1,0,'astral').total,before-1);});
t('Fraktionsgebundene Rüstung ist kein Ziel und Zauber bleibt auf der Hand',()=>{const s=S();s.players[1].equipment[0].weapon=null;s.players[1].equipment[0].armor=rt('Ubusa Brustpanzer',1);assert.equal(E.playOpenAzr(s,0,0).ok,false);assert.equal(s.players[0].hand[0],card(spell).bild);assert.equal(s.players[0].azr[0],null);});
t('Fraktionsgebundene Waffen ausgeschlossen',()=>{const s=S();s.players[1].equipment[0].weapon=rt('Parierdolch',1);assert.equal(E.playOpenAzr(s,0,0).ok,false);});
t('Verdeckte Rüstkammerkarten ausgeschlossen',()=>{const s=S();s.players[1].equipment[0].weapon=null;s.players[1].azr[0]=rt(staff,1,true);assert.equal(E.playOpenAzr(s,0,0).ok,false);});
for(const [name,kind] of [['Steinschwert','weapon'],['Holzschild','shield'],['Gedankenschleier Psythra','helmet']])t('Fraktionslose Ausrüstung: '+name,()=>{const s=S();s.players[1].equipment[0].weapon=null;s.players[1].equipment[0][kind]=rt(name,1);open(s);hit(s,name);assert.equal(s.players[1].equipment[0][kind],null);});
t('Eigene offene fraktionslose Karte ist ebenfalls zulässig',()=>{const s=S();s.players[1].equipment[0].weapon=null;s.players[0].equipment[0].weapon=rt(staff);open(s);hit(s);assert.equal(discarded(s.players[0],staff),1);});
t('Offene Reliquie in AZR: Zerstörung löst Fragmentbelohnung aus',()=>{const s=S();s.players[1].equipment[0].weapon=null;s.players[1].azr[1]=rt('Astralfragment der Ehre',1);open(s);hit(s,'Astralfragment der Ehre');assert.equal(s.players[1].azr[1],null);assert.equal(discarded(s.players[1],'Astralfragment der Ehre'),1);assert.equal(s.pendingBezEffect?.type,'fragment_reward');assert.equal(s.pendingBezEffect.sourcePlayer,1);const r=E.resolveFragmentReward(s,'0');assert(r.ok,r.msg);assert.equal(s.pendingBezEffect,null);});
t('Bezwingerinnen-Zielschutz schützt nicht die separat gewählte Waffe',()=>{const s=S();s.players[1].equipment[0].armor=rt('Mantel der Stille Dunkelglanz',1);s.players[1].bezSlots[0].effectState.strikelynProtection={enhanced:true};open(s);hit(s);assert(s.players[1].bezSlots[0]);assert(s.players[1].equipment[0].armor);});
t('Ungültige/manipulierte Ziel-ID zerstört keine Fraktionskarte',()=>{const s=S();s.players[1].equipment[0].armor=rt('Ubusa Brustpanzer',1);open(s);assert.equal(E.resolveNewAstralSpellTarget(s,'1|equipment|0|armor').ok,false);assert(s.players[1].equipment[0].armor);assert(s.pendingBezEffect);});
t('Verschwundenes oder verdecktes Ziel wird bei Auflösung erneut geprüft',()=>{for(const hide of [true,false]){const s=S();const ts=open(s),id=ts.find(t=>t.name.includes(staff)).id;if(hide)s.players[1].equipment[0].weapon.faceDown=true;else s.players[1].equipment[0].weapon=null;assert.equal(E.resolveNewAstralSpellTarget(s,id).ok,false);assert.equal(discarded(s.players[0],spell),0);}});
t('Verdeckt gesetzter Zauber lässt sich in der Versorgung aufdecken',()=>{const s=S();s.players[0].hand=[];s.players[0].azr[0]=rt(spell,0,true);const r=E.reveal(s,0);assert(r.ok,r.msg);hit(s);});
t('Angriffsreaktion zerstört Stab vor der Kampfauflösung',()=>{const s=S();s.activePlayer=1;s.phaseIndex=5;s.players[0].hand=[];s.players[0].azr[0]=rt(spell,0,true);let r=E.prepareAttack(s,0,{type:'bez',slot:0},'physical');assert(r.ok,r.msg);r=E.revealDefenderCard(s,0);assert(r.ok,r.msg);hit(s);assert.equal(s.players[1].equipment[0].weapon,null);assert.equal(s.pendingDamage,null);assert(E.confirmAttack(s).ok);});
t('KI wählt gegnerischen Stab vor eigener fraktionsloser Ausrüstung',()=>{const s=S();s.players[0].hand=[];s.players[1].azr[0]=rt(spell,1);s.players[0].equipment[0].weapon=rt(staff,0);assert(E.startInstantAstralSpell(s,1,0).ok);assert(G5AI.resolvePending(s).ok);assert.equal(s.players[0].equipment[0].weapon,null);assert(s.players[1].equipment[0].weapon);});
console.log(`RESULT ${pass} PASS / ${fail} FAIL`);if(fail)process.exitCode=1;
